### ISSUE TITLE
Zip file contents for version 3 board are missing contents (except for checksums).

### ISSUE THREAD

**Issue by ECArick** [Future-Electronics-Design-Center/Avalanche-Eval-Board#2]
I downloaded the latest repository and upon opening the zip files for the demo projects for the version 3 board, found they are 1KB in size and only contain checksums.

**Comment by Future-Electronics-Design-Center** [comment]
Per our phone call I believe you were able to download the project files for the Avalanche Rev 3 PF_ADC_Demo correct?  I will close this issue for now.   If you have any issues going forward please re-open a new issue and we'll get it sorted for you.
